export enum PostTypes {
  DEFAULT = 'DEFAULT',
  MADE_REFERRAL = 'MADE_REFERRAL',
  UPDATED_PROFILE = 'UPDATED_PROFILE',
  LIKED_POST = 'LIKED_POST',
  COMMENTED_ON_POST = 'COMMENTED_ON_POST',
  SHARED_POST = 'SHARED_POST',
}
